name: Test output being sent to webhook

on:
  - push
env:
  GITHUB_SHA: ${{ github.sha }}
  REGISTRY_URL: us.icr.io
  IMAGE_NAME: dts-ce-py-app
  REGISTRY_NAMESPACE: rtiffany

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
        output1: ${{ steps.step1.outputs.test }}
        output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "image=${{ env.IMAGE_NAME }}" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "tag=${{ env.GITHUB_SHA }}" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"